import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { LayoutDashboard, FolderOpen, Globe2, BarChart3, Images, Mail, User, Settings, Sun, Moon, LogOut, Plus, ArrowUpRight } from 'lucide-react';
import ProjectEditor from './ProjectEditor';
import LiveWebsiteEditor from './LiveWebsiteEditor';
import Cover from './Cover';
import { cms, uploadMedia } from './cms';
import './admin.css';
const sections=[['Dashboard',LayoutDashboard],['Projects',FolderOpen],['Live Websites',Globe2],['Analytics',BarChart3],['Media Library',Images],['Messages',Mail],['Profile',User],['Website Settings',Settings]] as const;
const date=(v:string)=>v?new Date(v).toLocaleString():'Not recorded';
function Bars({title,items=[]}:{title:string;items?:any[]}){const max=Math.max(1,...items.map(i=>Number(i.value)));return <section className="cms-panel"><h2>{title}</h2>{!items.length?<p className="cms-empty">No recorded activity yet.</p>:<ul className="cms-bars">{items.slice(0,10).map(i=><li key={i.label}><div><span>{i.label.replaceAll('_',' ')}</span><strong>{Number(i.value).toLocaleString()}</strong></div><meter min={0} max={max} value={i.value} aria-label={`${i.label}: ${i.value}`}/></li>)}</ul>}</section>;}
function Trend({data=[]}:{data?:any[]}){const max=Math.max(1,...data.map(d=>d.views));const points=data.map((d,i)=>`${i*700/Math.max(1,data.length-1)},${150-d.views*130/max}`).join(' ');return <section className="cms-panel cms-trend"><h2>Visitor activity</h2><p className="cms-muted">Page views by day · UTC</p>{data.some(d=>d.views)?<><svg viewBox="0 0 700 170" role="img" aria-label={`Daily page views, peak ${max}`}><path d="M0 20H700 M0 85H700 M0 150H700" stroke="currentColor" opacity=".12"/><polyline points={points} fill="none" stroke="var(--cms-accent)" strokeWidth="3"/></svg><div className="cms-between"><small>{data[0]?.date}</small><small>{data.at(-1)?.date}</small></div><details><summary>View daily values</summary><table><thead><tr><th>Date</th><th>Views</th><th>Unique visitors</th></tr></thead><tbody>{data.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.views}</td><td>{d.visitors}</td></tr>)}</tbody></table></details></>:<p className="cms-empty">Your traffic trend will appear after visitors arrive.</p>}</section>;}
export default function Admin(){
 const [section,setSection]=useState('Dashboard'),[theme,setTheme]=useState(()=>localStorage.getItem('cmsTheme')||'light');
 const [projects,setProjects]=useState<any[]>([]),[websites,setWebsites]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[profile,setProfile]=useState<any>(null),[settings,setSettings]=useState<any>(null),[analytics,setAnalytics]=useState<any>(null);
 const [days,setDays]=useState(30),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[editing,setEditing]=useState<any>(undefined),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError('');const results=await Promise.allSettled([cms('/admin/projects').then(setProjects),cms('/admin/websites').then(setWebsites),cms('/media').then(setMedia),cms('/messages').then(setMessages),cms('/profile').then(setProfile),cms('/settings').then(setSettings)]);const failed=results.find(r=>r.status==='rejected') as PromiseRejectedResult|undefined;if(failed)setError(failed.reason.message);setLoading(false);}
 useEffect(()=>{load();},[]);
 useEffect(()=>{let active=true;setAnalytics(null);cms('/analytics?days='+days).then(d=>{if(active)setAnalytics(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[days]);
 useEffect(()=>{localStorage.setItem('cmsTheme',theme);},[theme]);
 async function act(fn:()=>Promise<any>,message:string){setBusy(true);setError('');setNotice('');try{await fn();setNotice(message);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const go=(name:string)=>{if(editing!==undefined&&!confirm('Leave the editor? Unsaved changes will be lost.'))return;setEditing(undefined);setSection(name);setSearch('');setNotice('');};
 const stats=[['Total visitors',analytics?.totalVisitors,'Visits / sessions'],['Unique visitors',analytics?.uniqueVisitors,'Anonymous browser IDs'],['Page views',analytics?.pageViews,'All portfolio pages'],['Project views',analytics?.projectViews,'Case study visits']];
 return <div className={`cms ${theme==='dark'?'cms-dark':''}`}><aside className="cms-sidebar"><Link className="cms-brand" to="/">SA<span>Saadux<small>PORTFOLIO STUDIO</small></span></Link><p className="cms-eyebrow">WORKSPACE</p><nav aria-label="Admin navigation">{sections.map(([name,Icon])=><button key={name} className={section===name?'active':''} aria-current={section===name?'page':undefined} onClick={()=>go(name)}><Icon size={19}/>{name}{name==='Messages'&&messages.some(m=>m.status==='unread')&&<span className="cms-count">{messages.filter(m=>m.status==='unread').length}</span>}</button>)}</nav><div className="cms-sidebar-bottom"><Link to="/">View portfolio <ArrowUpRight size={16}/></Link><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>} {theme==='dark'?'Light':'Dark'} appearance</button><button onClick={()=>{localStorage.removeItem('adminToken');window.location.assign('/login');}}><LogOut size={18}/>Sign out</button></div></aside>
 <main className="cms-main"><header className="cms-top"><span>Portfolio / {section}</span><span>{profile?.username||'Admin'}</span></header>
 {error&&<div role="alert" className="cms-error">{error} <button onClick={load}>Retry</button></div>}{notice&&<p role="status" className="cms-notice">{notice}</p>}
 {editing!==undefined?(section==='Live Websites'?<LiveWebsiteEditor website={editing} onCancel={()=>setEditing(undefined)} onSave={async(data:any)=>{await cms(editing?`/websites/${editing.id}`:'/websites',{method:editing?'PUT':'POST',body:JSON.stringify(data)});setWebsites(await cms('/admin/websites'));setEditing(undefined);setNotice('Website saved.');}}/>:<ProjectEditor project={editing} onCancel={()=>setEditing(undefined)} onSave={async(data:any)=>{await cms(editing?`/projects/${editing.id}`:'/projects',{method:editing?'PUT':'POST',body:JSON.stringify(data)});setProjects(await cms('/admin/projects'));setEditing(undefined);setNotice('Project saved.');}}/>):<>
 <div className="cms-heading"><div><p className="cms-eyebrow">YOUR PORTFOLIO, MANAGED.</p><h1>{section==='Dashboard'?'Your studio at a glance.':section}</h1><p className="cms-muted">{section==='Dashboard'?'Keep your work current. See what connects with visitors.':section==='Projects'?'Organise your case studies and choose what goes live.':section==='Live Websites'?'Manage the websites displayed in your live work gallery.':section==='Media Library'?'One place for the images and videos behind your work.':''}</p></div><div className="cms-actions">{['Dashboard','Analytics'].includes(section)&&<select aria-label="Analytics period" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>Last {n} days</option>)}</select>}{['Dashboard','Projects'].includes(section)&&<button className="cms-primary" onClick={()=>{setSection('Projects');setEditing(null);}}><Plus size={17}/>New project</button>}{section==='Live Websites'&&<button className="cms-primary" onClick={()=>setEditing(null)}><Plus size={17}/>New website</button>}</div></div>
 {loading&&<p role="status">Loading your workspace…</p>}
 {['Dashboard','Analytics'].includes(section)&&<><div className="cms-stats">{stats.map(([label,value,help])=><section className="cms-panel" key={label}><p>{label}</p><strong>{value===undefined?'—':Number(value).toLocaleString()}</strong><small>{help}</small></section>)}</div><div className="cms-two"><Trend data={analytics?.trend}/><Bars title="Most viewed projects" items={analytics?.projects?.map((x:any)=>({...x,label:projects.find(p=>String(p.id)===x.label)?.title||x.label}))}/></div>{section==='Analytics'&&<><p className="cms-muted">Visitors are estimates based on anonymous browser IDs. Locations appear only when the host supplies them. Resume downloads count clicks on the resume link.</p><div className="cms-two">{[['Top pages','pages'],['Project and contact actions','actions'],['Devices','devices'],['Traffic sources','sources'],['Countries','countries'],['Cities','cities']].map(([title,key])=><Bars key={key} title={title} items={analytics?.[key]}/>)}</div></>}</>}
 {['Dashboard','Projects'].includes(section)&&<section className="cms-panel"><div className="cms-between"><h2>{section==='Dashboard'?'Your projects':'Project library'}</h2><span className="cms-muted">{projects.length} projects</span></div><div className="cms-filters"><input aria-label="Search projects" placeholder="Search projects…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Drafts</option></select></div><div className="cms-table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Homepage</th><th>Order</th><th>Actions</th></tr></thead><tbody>{projects.filter(p=>`${p.title} ${p.tag}`.toLowerCase().includes(search.toLowerCase())&&(status==='all'||(status==='published'?p.published:!p.published))).map(p=><tr key={p.id}><td><div className="cms-project-cell"><div className="cms-thumb"><Cover project={p}/></div><div><strong>{p.title}</strong><small>{p.tag} · {p.year}{p.featured?' · Featured':''}</small></div></div></td><td><span className={`cms-badge ${p.published?'published':''}`}>{p.published?'Published':'Draft'}</span></td><td>{p.homepage_visible?'Visible':'Hidden'}</td><td>{p.sort_order}</td><td><div className="cms-actions"><button onClick={()=>{setSection('Projects');setEditing(p);}}>Edit</button><button disabled={busy} onClick={()=>act(async()=>{await cms(`/projects/${p.id}`,{method:'PUT',body:JSON.stringify({...p,published:!p.published})});setProjects(await cms('/admin/projects'));},'Publishing status updated.')}>{p.published?'Unpublish':'Publish'}</button><button className="cms-danger" disabled={busy} onClick={()=>{if(confirm(`Delete “${p.title}”? This cannot be undone.`))act(async()=>{await cms(`/projects/${p.id}`,{method:'DELETE'});setProjects(await cms('/admin/projects'));},'Project deleted.');}}>Delete</button></div></td></tr>)}</tbody></table></div>{!projects.length&&!loading&&<p className="cms-empty">No projects yet. Create your first case study.</p>}</section>}
 {section==='Live Websites'&&<section className="cms-panel"><div className="cms-between"><h2>Live website library</h2><span className="cms-muted">{websites.length} websites</span></div><div className="cms-filters"><input aria-label="Search websites" placeholder="Search websites…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Hidden</option></select></div><div className="cms-table-wrap"><table><thead><tr><th>Website</th><th>Preview</th><th>Status</th><th>Order</th><th>Actions</th></tr></thead><tbody>{websites.filter(w=>`${w.title} ${w.category}`.toLowerCase().includes(search.toLowerCase())&&(status==='all'||(status==='published'?w.published:!w.published))).map(w=><tr key={w.id}><td><div className="cms-project-cell"><div className="cms-thumb">{w.preview_type==='video'?<video src={w.video_url} poster={w.poster_url||w.image_url||undefined} muted playsInline preload="metadata"/>:<img src={w.image_url} alt=""/>}</div><div><strong>{w.title}</strong><small>{w.category}</small></div></div></td><td>{w.preview_type==='video'?'Video':'Image'}</td><td><span className={`cms-badge ${w.published?'published':''}`}>{w.published?'Published':'Hidden'}</span></td><td>{w.sort_order}</td><td><div className="cms-actions"><button onClick={()=>setEditing(w)}>Edit</button><button disabled={busy} onClick={()=>act(async()=>{await cms(`/websites/${w.id}`,{method:'PUT',body:JSON.stringify({...w,published:!w.published})});setWebsites(await cms('/admin/websites'));},'Website visibility updated.')}>{w.published?'Hide':'Publish'}</button><button className="cms-danger" disabled={busy} onClick={()=>{if(confirm(`Delete “${w.title}”? This cannot be undone.`))act(async()=>{await cms(`/websites/${w.id}`,{method:'DELETE'});setWebsites(await cms('/admin/websites'));},'Website deleted.');}}>Delete</button></div></td></tr>)}</tbody></table></div>{!websites.length&&!loading&&<p className="cms-empty">Add your first live website.</p>}</section>}
 {section==='Media Library'&&<><div className="cms-filters"><input aria-label="Search media" placeholder="Search filenames…" value={search} onChange={e=>setSearch(e.target.value)}/><label className="cms-upload">Upload media<input aria-label="Upload media" type="file" accept="image/jpeg,image/png,image/webp,video/mp4" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)act(async()=>{await uploadMedia(f);setMedia(await cms('/media'));},'Media uploaded.');e.target.value='';}}/></label></div><p className="cms-muted">JPG, PNG, WEBP and MP4 · Up to 4 MB. Larger videos can be added by URL in the project editor.</p><div className="cms-media-grid">{media.filter(m=>m.name.toLowerCase().includes(search.toLowerCase())).map(m=><article className="cms-panel" key={m.id}><div className="cms-media-preview">{m.kind==='video'?<video src={m.url} controls muted playsInline preload="metadata"/>:<img src={m.url} alt={m.name} loading="lazy"/>}</div><h3>{m.name}</h3><p className="cms-muted">{m.kind} · {(m.bytes/1024/1024).toFixed(2)} MB</p><div className="cms-actions"><button onClick={()=>act(()=>navigator.clipboard.writeText(m.url),'URL copied. Paste it into a project or profile.')}>Copy URL</button><button className="cms-danger" disabled={busy} onClick={()=>{if(confirm(`Delete “${m.name}” permanently?`))act(async()=>{await cms(`/media/${m.id}`,{method:'DELETE'});setMedia(await cms('/media'));},'Media deleted.');}}>Delete</button></div></article>)}</div>{!media.length&&!loading&&<p className="cms-empty">Upload an image or video to start your library.</p>}</>}
 {section==='Messages'&&<section className="cms-panel"><h2>Portfolio enquiries</h2>{!messages.length&&<p className="cms-empty">Messages from your portfolio contact form will appear here.</p>}{messages.map(m=><article className="cms-message" key={m.id}><div className="cms-between"><h3>{m.name}</h3><span className="cms-badge">{m.status}</span></div><p className="cms-muted">{m.email} · {date(m.created_at)}</p><p className="cms-message-body">{m.message}</p><div className="cms-actions"><a href={`mailto:${m.email}`}>Reply by email ↗</a><button disabled={busy} onClick={()=>act(async()=>{await cms(`/messages/${m.id}`,{method:'PATCH',body:JSON.stringify({status:m.status==='read'?'unread':'read'})});setMessages(await cms('/messages'));},'Message updated.')}>Mark {m.status==='read'?'unread':'read'}</button></div></article>)}</section>}
 {section==='Profile'&&profile&&<form className="cms-panel cms-account" onSubmit={e=>{e.preventDefault();act(async()=>{const next=await cms('/profile',{method:'PUT',body:JSON.stringify(profile)});if(next.reauthenticate){localStorage.removeItem('adminToken');window.location.assign('/login');}else setProfile(next);},'Profile saved.');}}><h2>Account settings</h2>{profile.avatar_url&&<img className="cms-avatar" src={profile.avatar_url} alt="Your profile"/>}<div className="cms-fields">{[['username','Username'],['email','Email'],['avatar_url','Profile image URL']].map(([key,label])=><label key={key}>{label}<input type={key==='email'?'email':'text'} required={key==='username'} value={profile[key]||''} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<label>Upload profile image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)act(async()=>{const m=await uploadMedia(file);setProfile({...profile,avatar_url:m.url});},'Image uploaded. Save your profile to apply it.');}}/></label></div><p className="cms-muted">Created: {date(profile.created_at)}<br/>Last login: {date(profile.last_login)}</p><h2>Change password</h2><div className="cms-fields"><label>Current password<input type="password" autoComplete="current-password" value={profile.current_password||''} onChange={e=>setProfile({...profile,current_password:e.target.value})}/></label><label>New password<input type="password" autoComplete="new-password" minLength={12} value={profile.new_password||''} onChange={e=>setProfile({...profile,new_password:e.target.value})}/></label></div><p className="cms-muted">Use at least 12 characters. Changing your password signs out existing sessions.</p><button className="cms-primary" disabled={busy}>Save account settings</button></form>}
 {section==='Website Settings'&&settings&&<form className="cms-panel cms-account" onSubmit={e=>{e.preventDefault();act(async()=>setSettings(await cms('/settings',{method:'PUT',body:JSON.stringify(settings)})),'Website settings saved.');}}><h2>Portfolio settings</h2><label>Contact email<input type="email" value={settings.contact_email} onChange={e=>setSettings({...settings,contact_email:e.target.value})}/></label><label>Resume URL<input type="url" value={settings.resume_url} onChange={e=>setSettings({...settings,resume_url:e.target.value})}/></label><label className="cms-check"><input type="checkbox" checked={settings.analytics_enabled} onChange={e=>setSettings({...settings,analytics_enabled:e.target.checked})}/>Collect portfolio analytics</label><p className="cms-muted">Blank URLs retain the portfolio's current links. Analytics starts collecting new activity when enabled.</p><button className="cms-primary" disabled={busy}>Save website settings</button></form>}
 </>}
 </main></div>;
}
